-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity main is
port (
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC );
end;


architecture behav of main is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "main,hls_ip_2018_2_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.196000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2018_2_2}";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal module_dpValues_Val_s_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal module_dpValues_Val_s_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal module_keys_Val_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal module_values_Val_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal module_values_Val_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_fu_88_result1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_fu_88_result2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_fu_88_outputReady : STD_LOGIC;

    component xtea IS
    port (
        ap_rst : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        op1 : IN STD_LOGIC_VECTOR (31 downto 0);
        op2 : IN STD_LOGIC_VECTOR (31 downto 0);
        command : IN STD_LOGIC_VECTOR (1 downto 0);
        inputReady : IN STD_LOGIC;
        result1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        result2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        outputReady : OUT STD_LOGIC );
    end component;


    component main_module_dpValbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component main_module_keys_cud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin



    ap_return <= ap_const_lv32_0;
end behav;
