-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity xtea is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    clock : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    op1 : IN STD_LOGIC_VECTOR (31 downto 0);
    op2 : IN STD_LOGIC_VECTOR (31 downto 0);
    command : IN STD_LOGIC_VECTOR (1 downto 0);
    inputReady : IN STD_LOGIC;
    result1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    result2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    outputReady : OUT STD_LOGIC );
end;


architecture behav of xtea is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "xtea,hls_ip_2018_2_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.196000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=300,HLS_SYN_LUT=1083,HLS_VERSION=2018_2_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal dpValues_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal dpValues_ce0 : STD_LOGIC;
    signal dpValues_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dpValues_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal dpValues_ce1 : STD_LOGIC;
    signal dpValues_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal keys_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal keys_ce0 : STD_LOGIC;
    signal keys_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal values_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal values_ce0 : STD_LOGIC;
    signal values_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal values_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal values_ce1 : STD_LOGIC;
    signal values_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xtea_ssdm_thread_s_load_fu_194_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal xtea_ssdm_thread_1_load_fu_198_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_xtea_fsm_fu_114_dpValues_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xtea_fsm_fu_114_dpValues_ce0 : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_dpValues_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xtea_fsm_fu_114_dpValues_ce1 : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_keys_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_xtea_fsm_fu_114_keys_ce0 : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_keys_we0 : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_keys_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_fsm_fu_114_keys_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_xtea_fsm_fu_114_keys_ce1 : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_keys_we1 : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_keys_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_fsm_fu_114_values_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xtea_fsm_fu_114_values_ce0 : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_values_we0 : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_values_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_fsm_fu_114_values_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xtea_fsm_fu_114_values_ce1 : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_values_we1 : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_values_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_fsm_fu_114_memCommand : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_xtea_fsm_fu_114_memCommand_ap_vld : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_fsmState_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_fsm_fu_114_fsmState_o_ap_vld : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_result1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_fsm_fu_114_result1_ap_vld : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_result2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_fsm_fu_114_result2_ap_vld : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_outputReady : STD_LOGIC;
    signal grp_xtea_fsm_fu_114_outputReady_ap_vld : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_counter_o : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_xtea_datapath_fu_154_counter_o_ap_vld : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_sum_o : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xtea_datapath_fu_154_sum_o_ap_vld : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_temp_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_datapath_fu_154_temp_o_ap_vld : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_acc_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_datapath_fu_154_acc_o_ap_vld : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_dpValues_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xtea_datapath_fu_154_dpValues_ce0 : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_dpValues_we0 : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_dpValues_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_datapath_fu_154_dpValues_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xtea_datapath_fu_154_dpValues_ce1 : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_dpValues_we1 : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_dpValues_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xtea_datapath_fu_154_keys_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_xtea_datapath_fu_154_keys_ce0 : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_values_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xtea_datapath_fu_154_values_ce0 : STD_LOGIC;
    signal grp_xtea_datapath_fu_154_values_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xtea_datapath_fu_154_values_ce1 : STD_LOGIC;
    signal counter : STD_LOGIC_VECTOR (5 downto 0);
    signal sum : STD_LOGIC_VECTOR (63 downto 0);
    signal temp : STD_LOGIC_VECTOR (31 downto 0);
    signal acc : STD_LOGIC_VECTOR (31 downto 0);
    signal fsmState : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";

    component xtea_fsm IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        counter : IN STD_LOGIC_VECTOR (5 downto 0);
        dpValues_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        dpValues_ce0 : OUT STD_LOGIC;
        dpValues_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        dpValues_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        dpValues_ce1 : OUT STD_LOGIC;
        dpValues_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        keys_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        keys_ce0 : OUT STD_LOGIC;
        keys_we0 : OUT STD_LOGIC;
        keys_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        keys_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        keys_ce1 : OUT STD_LOGIC;
        keys_we1 : OUT STD_LOGIC;
        keys_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        values_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        values_ce0 : OUT STD_LOGIC;
        values_we0 : OUT STD_LOGIC;
        values_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        values_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        values_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        values_ce1 : OUT STD_LOGIC;
        values_we1 : OUT STD_LOGIC;
        values_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        values_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        memCommand : OUT STD_LOGIC_VECTOR (1 downto 0);
        memCommand_ap_vld : OUT STD_LOGIC;
        fsmState_i : IN STD_LOGIC_VECTOR (31 downto 0);
        fsmState_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        fsmState_o_ap_vld : OUT STD_LOGIC;
        reset : IN STD_LOGIC;
        op1 : IN STD_LOGIC_VECTOR (31 downto 0);
        op2 : IN STD_LOGIC_VECTOR (31 downto 0);
        command : IN STD_LOGIC_VECTOR (1 downto 0);
        inputReady : IN STD_LOGIC;
        result1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        result1_ap_vld : OUT STD_LOGIC;
        result2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        result2_ap_vld : OUT STD_LOGIC;
        outputReady : OUT STD_LOGIC;
        outputReady_ap_vld : OUT STD_LOGIC );
    end component;


    component xtea_datapath IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        counter_i : IN STD_LOGIC_VECTOR (5 downto 0);
        counter_o : OUT STD_LOGIC_VECTOR (5 downto 0);
        counter_o_ap_vld : OUT STD_LOGIC;
        sum_i : IN STD_LOGIC_VECTOR (63 downto 0);
        sum_o : OUT STD_LOGIC_VECTOR (63 downto 0);
        sum_o_ap_vld : OUT STD_LOGIC;
        temp_i : IN STD_LOGIC_VECTOR (31 downto 0);
        temp_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        temp_o_ap_vld : OUT STD_LOGIC;
        acc_i : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_o_ap_vld : OUT STD_LOGIC;
        dpValues_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        dpValues_ce0 : OUT STD_LOGIC;
        dpValues_we0 : OUT STD_LOGIC;
        dpValues_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dpValues_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        dpValues_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        dpValues_ce1 : OUT STD_LOGIC;
        dpValues_we1 : OUT STD_LOGIC;
        dpValues_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        keys_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        keys_ce0 : OUT STD_LOGIC;
        keys_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        values_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        values_ce0 : OUT STD_LOGIC;
        values_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        values_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        values_ce1 : OUT STD_LOGIC;
        values_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        fsmState : IN STD_LOGIC_VECTOR (31 downto 0);
        command : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component xtea_dpValues IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component xtea_keys IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    dpValues_U : component xtea_dpValues
    generic map (
        DataWidth => 32,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dpValues_address0,
        ce0 => dpValues_ce0,
        we0 => grp_xtea_datapath_fu_154_dpValues_we0,
        d0 => grp_xtea_datapath_fu_154_dpValues_d0,
        q0 => dpValues_q0,
        address1 => dpValues_address1,
        ce1 => dpValues_ce1,
        we1 => grp_xtea_datapath_fu_154_dpValues_we1,
        d1 => grp_xtea_datapath_fu_154_dpValues_d1,
        q1 => dpValues_q1);

    keys_U : component xtea_keys
    generic map (
        DataWidth => 32,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => keys_address0,
        ce0 => keys_ce0,
        we0 => grp_xtea_fsm_fu_114_keys_we0,
        d0 => grp_xtea_fsm_fu_114_keys_d0,
        q0 => keys_q0,
        address1 => grp_xtea_fsm_fu_114_keys_address1,
        ce1 => grp_xtea_fsm_fu_114_keys_ce1,
        we1 => grp_xtea_fsm_fu_114_keys_we1,
        d1 => grp_xtea_fsm_fu_114_keys_d1);

    values_U : component xtea_dpValues
    generic map (
        DataWidth => 32,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => values_address0,
        ce0 => values_ce0,
        we0 => grp_xtea_fsm_fu_114_values_we0,
        d0 => grp_xtea_fsm_fu_114_values_d0,
        q0 => values_q0,
        address1 => values_address1,
        ce1 => values_ce1,
        we1 => grp_xtea_fsm_fu_114_values_we1,
        d1 => grp_xtea_fsm_fu_114_values_d1,
        q1 => values_q1);

    grp_xtea_fsm_fu_114 : component xtea_fsm
    port map (
        ap_clk => clock,
        ap_rst => ap_rst,
        counter => counter,
        dpValues_address0 => grp_xtea_fsm_fu_114_dpValues_address0,
        dpValues_ce0 => grp_xtea_fsm_fu_114_dpValues_ce0,
        dpValues_q0 => dpValues_q0,
        dpValues_address1 => grp_xtea_fsm_fu_114_dpValues_address1,
        dpValues_ce1 => grp_xtea_fsm_fu_114_dpValues_ce1,
        dpValues_q1 => dpValues_q1,
        keys_address0 => grp_xtea_fsm_fu_114_keys_address0,
        keys_ce0 => grp_xtea_fsm_fu_114_keys_ce0,
        keys_we0 => grp_xtea_fsm_fu_114_keys_we0,
        keys_d0 => grp_xtea_fsm_fu_114_keys_d0,
        keys_address1 => grp_xtea_fsm_fu_114_keys_address1,
        keys_ce1 => grp_xtea_fsm_fu_114_keys_ce1,
        keys_we1 => grp_xtea_fsm_fu_114_keys_we1,
        keys_d1 => grp_xtea_fsm_fu_114_keys_d1,
        values_address0 => grp_xtea_fsm_fu_114_values_address0,
        values_ce0 => grp_xtea_fsm_fu_114_values_ce0,
        values_we0 => grp_xtea_fsm_fu_114_values_we0,
        values_d0 => grp_xtea_fsm_fu_114_values_d0,
        values_q0 => values_q0,
        values_address1 => grp_xtea_fsm_fu_114_values_address1,
        values_ce1 => grp_xtea_fsm_fu_114_values_ce1,
        values_we1 => grp_xtea_fsm_fu_114_values_we1,
        values_d1 => grp_xtea_fsm_fu_114_values_d1,
        values_q1 => values_q1,
        memCommand => grp_xtea_fsm_fu_114_memCommand,
        memCommand_ap_vld => grp_xtea_fsm_fu_114_memCommand_ap_vld,
        fsmState_i => fsmState,
        fsmState_o => grp_xtea_fsm_fu_114_fsmState_o,
        fsmState_o_ap_vld => grp_xtea_fsm_fu_114_fsmState_o_ap_vld,
        reset => reset,
        op1 => op1,
        op2 => op2,
        command => command,
        inputReady => inputReady,
        result1 => grp_xtea_fsm_fu_114_result1,
        result1_ap_vld => grp_xtea_fsm_fu_114_result1_ap_vld,
        result2 => grp_xtea_fsm_fu_114_result2,
        result2_ap_vld => grp_xtea_fsm_fu_114_result2_ap_vld,
        outputReady => grp_xtea_fsm_fu_114_outputReady,
        outputReady_ap_vld => grp_xtea_fsm_fu_114_outputReady_ap_vld);

    grp_xtea_datapath_fu_154 : component xtea_datapath
    port map (
        ap_clk => clock,
        ap_rst => ap_rst,
        counter_i => counter,
        counter_o => grp_xtea_datapath_fu_154_counter_o,
        counter_o_ap_vld => grp_xtea_datapath_fu_154_counter_o_ap_vld,
        sum_i => sum,
        sum_o => grp_xtea_datapath_fu_154_sum_o,
        sum_o_ap_vld => grp_xtea_datapath_fu_154_sum_o_ap_vld,
        temp_i => temp,
        temp_o => grp_xtea_datapath_fu_154_temp_o,
        temp_o_ap_vld => grp_xtea_datapath_fu_154_temp_o_ap_vld,
        acc_i => acc,
        acc_o => grp_xtea_datapath_fu_154_acc_o,
        acc_o_ap_vld => grp_xtea_datapath_fu_154_acc_o_ap_vld,
        dpValues_address0 => grp_xtea_datapath_fu_154_dpValues_address0,
        dpValues_ce0 => grp_xtea_datapath_fu_154_dpValues_ce0,
        dpValues_we0 => grp_xtea_datapath_fu_154_dpValues_we0,
        dpValues_d0 => grp_xtea_datapath_fu_154_dpValues_d0,
        dpValues_q0 => dpValues_q0,
        dpValues_address1 => grp_xtea_datapath_fu_154_dpValues_address1,
        dpValues_ce1 => grp_xtea_datapath_fu_154_dpValues_ce1,
        dpValues_we1 => grp_xtea_datapath_fu_154_dpValues_we1,
        dpValues_d1 => grp_xtea_datapath_fu_154_dpValues_d1,
        keys_address0 => grp_xtea_datapath_fu_154_keys_address0,
        keys_ce0 => grp_xtea_datapath_fu_154_keys_ce0,
        keys_q0 => keys_q0,
        values_address0 => grp_xtea_datapath_fu_154_values_address0,
        values_ce0 => grp_xtea_datapath_fu_154_values_ce0,
        values_q0 => values_q0,
        values_address1 => grp_xtea_datapath_fu_154_values_address1,
        values_ce1 => grp_xtea_datapath_fu_154_values_ce1,
        values_q1 => values_q1,
        fsmState => fsmState,
        command => command);





    acc_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if ((grp_xtea_datapath_fu_154_acc_o_ap_vld = ap_const_logic_1)) then 
                acc <= grp_xtea_datapath_fu_154_acc_o;
            end if; 
        end if;
    end process;


    counter_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if ((grp_xtea_datapath_fu_154_counter_o_ap_vld = ap_const_logic_1)) then 
                counter <= grp_xtea_datapath_fu_154_counter_o;
            end if; 
        end if;
    end process;


    fsmState_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if ((grp_xtea_fsm_fu_114_fsmState_o_ap_vld = ap_const_logic_1)) then 
                fsmState <= grp_xtea_fsm_fu_114_fsmState_o;
            end if; 
        end if;
    end process;


    outputReady_assign_proc : process(clock)
    begin
        if (clock'event and clock =  '1') then
            if ((grp_xtea_fsm_fu_114_outputReady_ap_vld = ap_const_logic_1)) then 
                outputReady <= grp_xtea_fsm_fu_114_outputReady;
            end if; 
        end if;
    end process;


    result1_assign_proc : process(clock)
    begin
        if (clock'event and clock =  '1') then
            if ((grp_xtea_fsm_fu_114_result1_ap_vld = ap_const_logic_1)) then 
                result1 <= grp_xtea_fsm_fu_114_result1;
            end if; 
        end if;
    end process;


    result2_assign_proc : process(clock)
    begin
        if (clock'event and clock =  '1') then
            if ((grp_xtea_fsm_fu_114_result2_ap_vld = ap_const_logic_1)) then 
                result2 <= grp_xtea_fsm_fu_114_result2;
            end if; 
        end if;
    end process;


    sum_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if ((grp_xtea_datapath_fu_154_sum_o_ap_vld = ap_const_logic_1)) then 
                sum <= grp_xtea_datapath_fu_154_sum_o;
            end if; 
        end if;
    end process;


    temp_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if ((grp_xtea_datapath_fu_154_temp_o_ap_vld = ap_const_logic_1)) then 
                temp <= grp_xtea_datapath_fu_154_temp_o;
            end if; 
        end if;
    end process;

    ap_CS_fsm <= ap_const_lv4_0;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    dpValues_address0_assign_proc : process(grp_xtea_fsm_fu_114_dpValues_address0, grp_xtea_fsm_fu_114_dpValues_ce0, grp_xtea_datapath_fu_154_dpValues_address0, grp_xtea_datapath_fu_154_dpValues_ce0)
    begin
        if ((grp_xtea_datapath_fu_154_dpValues_ce0 = ap_const_logic_1)) then 
            dpValues_address0 <= grp_xtea_datapath_fu_154_dpValues_address0;
        elsif ((grp_xtea_fsm_fu_114_dpValues_ce0 = ap_const_logic_1)) then 
            dpValues_address0 <= grp_xtea_fsm_fu_114_dpValues_address0;
        else 
            dpValues_address0 <= "X";
        end if; 
    end process;


    dpValues_address1_assign_proc : process(grp_xtea_fsm_fu_114_dpValues_address1, grp_xtea_fsm_fu_114_dpValues_ce1, grp_xtea_datapath_fu_154_dpValues_address1, grp_xtea_datapath_fu_154_dpValues_ce1)
    begin
        if ((grp_xtea_datapath_fu_154_dpValues_ce1 = ap_const_logic_1)) then 
            dpValues_address1 <= grp_xtea_datapath_fu_154_dpValues_address1;
        elsif ((grp_xtea_fsm_fu_114_dpValues_ce1 = ap_const_logic_1)) then 
            dpValues_address1 <= grp_xtea_fsm_fu_114_dpValues_address1;
        else 
            dpValues_address1 <= "X";
        end if; 
    end process;


    dpValues_ce0_assign_proc : process(grp_xtea_fsm_fu_114_dpValues_ce0, grp_xtea_datapath_fu_154_dpValues_ce0)
    begin
        if ((grp_xtea_datapath_fu_154_dpValues_ce0 = ap_const_logic_1)) then 
            dpValues_ce0 <= grp_xtea_datapath_fu_154_dpValues_ce0;
        elsif ((grp_xtea_fsm_fu_114_dpValues_ce0 = ap_const_logic_1)) then 
            dpValues_ce0 <= grp_xtea_fsm_fu_114_dpValues_ce0;
        else 
            dpValues_ce0 <= 'X';
        end if; 
    end process;


    dpValues_ce1_assign_proc : process(grp_xtea_fsm_fu_114_dpValues_ce1, grp_xtea_datapath_fu_154_dpValues_ce1)
    begin
        if ((grp_xtea_datapath_fu_154_dpValues_ce1 = ap_const_logic_1)) then 
            dpValues_ce1 <= grp_xtea_datapath_fu_154_dpValues_ce1;
        elsif ((grp_xtea_fsm_fu_114_dpValues_ce1 = ap_const_logic_1)) then 
            dpValues_ce1 <= grp_xtea_fsm_fu_114_dpValues_ce1;
        else 
            dpValues_ce1 <= 'X';
        end if; 
    end process;


    keys_address0_assign_proc : process(grp_xtea_fsm_fu_114_keys_address0, grp_xtea_fsm_fu_114_keys_ce0, grp_xtea_datapath_fu_154_keys_address0, grp_xtea_datapath_fu_154_keys_ce0)
    begin
        if ((grp_xtea_datapath_fu_154_keys_ce0 = ap_const_logic_1)) then 
            keys_address0 <= grp_xtea_datapath_fu_154_keys_address0;
        elsif ((grp_xtea_fsm_fu_114_keys_ce0 = ap_const_logic_1)) then 
            keys_address0 <= grp_xtea_fsm_fu_114_keys_address0;
        else 
            keys_address0 <= "XX";
        end if; 
    end process;


    keys_ce0_assign_proc : process(grp_xtea_fsm_fu_114_keys_ce0, grp_xtea_datapath_fu_154_keys_ce0)
    begin
        if ((grp_xtea_datapath_fu_154_keys_ce0 = ap_const_logic_1)) then 
            keys_ce0 <= grp_xtea_datapath_fu_154_keys_ce0;
        elsif ((grp_xtea_fsm_fu_114_keys_ce0 = ap_const_logic_1)) then 
            keys_ce0 <= grp_xtea_fsm_fu_114_keys_ce0;
        else 
            keys_ce0 <= 'X';
        end if; 
    end process;


    values_address0_assign_proc : process(grp_xtea_fsm_fu_114_values_address0, grp_xtea_fsm_fu_114_values_ce0, grp_xtea_datapath_fu_154_values_address0, grp_xtea_datapath_fu_154_values_ce0)
    begin
        if ((grp_xtea_datapath_fu_154_values_ce0 = ap_const_logic_1)) then 
            values_address0 <= grp_xtea_datapath_fu_154_values_address0;
        elsif ((grp_xtea_fsm_fu_114_values_ce0 = ap_const_logic_1)) then 
            values_address0 <= grp_xtea_fsm_fu_114_values_address0;
        else 
            values_address0 <= "X";
        end if; 
    end process;


    values_address1_assign_proc : process(grp_xtea_fsm_fu_114_values_address1, grp_xtea_fsm_fu_114_values_ce1, grp_xtea_datapath_fu_154_values_address1, grp_xtea_datapath_fu_154_values_ce1)
    begin
        if ((grp_xtea_datapath_fu_154_values_ce1 = ap_const_logic_1)) then 
            values_address1 <= grp_xtea_datapath_fu_154_values_address1;
        elsif ((grp_xtea_fsm_fu_114_values_ce1 = ap_const_logic_1)) then 
            values_address1 <= grp_xtea_fsm_fu_114_values_address1;
        else 
            values_address1 <= "X";
        end if; 
    end process;


    values_ce0_assign_proc : process(grp_xtea_fsm_fu_114_values_ce0, grp_xtea_datapath_fu_154_values_ce0)
    begin
        if ((grp_xtea_datapath_fu_154_values_ce0 = ap_const_logic_1)) then 
            values_ce0 <= grp_xtea_datapath_fu_154_values_ce0;
        elsif ((grp_xtea_fsm_fu_114_values_ce0 = ap_const_logic_1)) then 
            values_ce0 <= grp_xtea_fsm_fu_114_values_ce0;
        else 
            values_ce0 <= 'X';
        end if; 
    end process;


    values_ce1_assign_proc : process(grp_xtea_fsm_fu_114_values_ce1, grp_xtea_datapath_fu_154_values_ce1)
    begin
        if ((grp_xtea_datapath_fu_154_values_ce1 = ap_const_logic_1)) then 
            values_ce1 <= grp_xtea_datapath_fu_154_values_ce1;
        elsif ((grp_xtea_fsm_fu_114_values_ce1 = ap_const_logic_1)) then 
            values_ce1 <= grp_xtea_fsm_fu_114_values_ce1;
        else 
            values_ce1 <= 'X';
        end if; 
    end process;

    xtea_ssdm_thread_1_load_fu_198_p1 <= ap_const_lv1_0;
    xtea_ssdm_thread_s_load_fu_194_p1 <= ap_const_lv1_0;
end behav;
