// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _main_HH_
#define _main_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "xtea.h"
#include "main_module_dpValbkb.h"
#include "main_module_keys_cud.h"

namespace ap_rtl {

struct main : public sc_module {
    // Port declarations 3
    sc_out< sc_lv<32> > ap_return;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    // Internal clock declarations for combination SystemC design. 
    sc_clock ap_sc_inter_clock;


    // Module declarations
    main(sc_module_name name);
    SC_HAS_PROCESS(main);

    ~main();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<32> > module_dpValues_Val_s_q0;
    sc_signal< sc_lv<32> > module_dpValues_Val_s_q1;
    sc_signal< sc_lv<32> > module_keys_Val_V_q0;
    sc_signal< sc_lv<32> > module_values_Val_V_q0;
    sc_signal< sc_lv<32> > module_values_Val_V_q1;
    sc_signal< sc_lv<32> > grp_xtea_fu_88_result1;
    sc_signal< sc_lv<32> > grp_xtea_fu_88_result2;
    sc_signal< sc_logic > grp_xtea_fu_88_outputReady;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_return();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
