// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "xtea_datapath.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic xtea_datapath::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic xtea_datapath::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> xtea_datapath::ap_ST_fsm_state1 = "1";
const sc_lv<2> xtea_datapath::ap_ST_fsm_state2 = "10";
const sc_lv<32> xtea_datapath::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> xtea_datapath::ap_const_lv32_E = "1110";
const sc_lv<32> xtea_datapath::ap_const_lv32_B = "1011";
const sc_lv<32> xtea_datapath::ap_const_lv32_9 = "1001";
const sc_lv<32> xtea_datapath::ap_const_lv32_A = "1010";
const sc_lv<32> xtea_datapath::ap_const_lv32_8 = "1000";
const sc_lv<32> xtea_datapath::ap_const_lv32_4 = "100";
const sc_lv<32> xtea_datapath::ap_const_lv32_7 = "111";
const sc_lv<32> xtea_datapath::ap_const_lv32_6 = "110";
const sc_lv<32> xtea_datapath::ap_const_lv32_D = "1101";
const sc_lv<32> xtea_datapath::ap_const_lv32_5 = "101";
const sc_lv<32> xtea_datapath::ap_const_lv32_C = "1100";
const sc_lv<32> xtea_datapath::ap_const_lv32_3 = "11";
const sc_lv<32> xtea_datapath::ap_const_lv32_1 = "1";
const sc_lv<64> xtea_datapath::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> xtea_datapath::ap_const_lv64_1 = "1";
const sc_lv<6> xtea_datapath::ap_const_lv6_0 = "000000";
const sc_lv<1> xtea_datapath::ap_const_lv1_0 = "0";
const sc_lv<1> xtea_datapath::ap_const_lv1_1 = "1";
const sc_lv<64> xtea_datapath::ap_const_lv64_C6EF3720 = "11000110111011110011011100100000";
const sc_lv<6> xtea_datapath::ap_const_lv6_1 = "1";
const sc_lv<64> xtea_datapath::ap_const_lv64_FFFFFFFF61C88647 = "1111111111111111111111111111111101100001110010001000011001000111";
const sc_lv<32> xtea_datapath::ap_const_lv32_1F = "11111";
const sc_lv<64> xtea_datapath::ap_const_lv64_9E3779B9 = "10011110001101110111100110111001";
const sc_lv<2> xtea_datapath::ap_const_lv2_2 = "10";
const sc_lv<2> xtea_datapath::ap_const_lv2_3 = "11";
const bool xtea_datapath::ap_const_boolean_1 = true;

xtea_datapath::xtea_datapath(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_o);
    sensitive << ( acc_i );
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( v_V_17_fu_473_p2 );
    sensitive << ( v_V_13_fu_529_p2 );

    SC_METHOD(thread_acc_o_ap_vld);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_CS_fsm);

    SC_METHOD(thread_ap_CS_fsm_state1);

    SC_METHOD(thread_ap_CS_fsm_state2);

    SC_METHOD(thread_ap_condition_171);
    sensitive << ( tmp_reg_548 );
    sensitive << ( tmp_8_fu_536_p2 );
    sensitive << ( tmp_7_fu_542_p2 );

    SC_METHOD(thread_counter_o);
    sensitive << ( counter_i );
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_fu_386_p2 );
    sensitive << ( tmp_8_fu_536_p2 );
    sensitive << ( tmp_7_fu_542_p2 );

    SC_METHOD(thread_counter_o_ap_vld);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_8_fu_536_p2 );
    sensitive << ( tmp_7_fu_542_p2 );

    SC_METHOD(thread_dpValues_address0);
    sensitive << ( tmp_read_fu_144_p2 );
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( xtea_dpValues_Val_V_9_gep_fu_234_p3 );
    sensitive << ( xtea_dpValues_Val_V_8_gep_fu_243_p3 );
    sensitive << ( xtea_dpValues_Val_V_6_gep_fu_266_p3 );
    sensitive << ( xtea_dpValues_Val_V_5_gep_fu_275_p3 );
    sensitive << ( xtea_dpValues_Val_V_14_gep_fu_319_p3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( xtea_dpValues_Val_V_12_gep_fu_328_p3 );
    sensitive << ( xtea_dpValues_Val_V_10_gep_fu_337_p3 );
    sensitive << ( xtea_dpValues_Val_V_7_gep_fu_346_p3 );
    sensitive << ( xtea_dpValues_Val_V_s_gep_fu_355_p3 );

    SC_METHOD(thread_dpValues_address1);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_dpValues_ce0);
    sensitive << ( tmp_read_fu_144_p2 );
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_dpValues_ce1);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_dpValues_d0);
    sensitive << ( values_q0 );
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_fu_379_p2 );
    sensitive << ( grp_fu_393_p2 );

    SC_METHOD(thread_dpValues_d1);
    sensitive << ( values_q1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_dpValues_we0);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_dpValues_we1);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_fu_379_p2);
    sensitive << ( acc_i );
    sensitive << ( dpValues_q0 );

    SC_METHOD(thread_grp_fu_386_p2);
    sensitive << ( counter_i );

    SC_METHOD(thread_grp_fu_393_p2);
    sensitive << ( acc_i );
    sensitive << ( dpValues_q0 );

    SC_METHOD(thread_keys_address0);
    sensitive << ( tmp_read_fu_144_p2 );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_3_fu_410_p1 );
    sensitive << ( tmp_9_fu_419_p1 );

    SC_METHOD(thread_keys_ce0);
    sensitive << ( tmp_read_fu_144_p2 );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_p_Result_1_fu_400_p4);
    sensitive << ( sum_i );

    SC_METHOD(thread_r_V_10_fu_431_p2);
    sensitive << ( dpValues_q0 );

    SC_METHOD(thread_r_V_11_fu_447_p1);
    sensitive << ( r_V_9_fu_437_p4 );

    SC_METHOD(thread_r_V_4_fu_451_p2);
    sensitive << ( r_V_10_fu_431_p2 );
    sensitive << ( r_V_11_fu_447_p1 );

    SC_METHOD(thread_r_V_6_fu_487_p2);
    sensitive << ( dpValues_q0 );

    SC_METHOD(thread_r_V_7_fu_493_p4);
    sensitive << ( dpValues_q0 );

    SC_METHOD(thread_r_V_8_fu_503_p1);
    sensitive << ( r_V_7_fu_493_p4 );

    SC_METHOD(thread_r_V_9_fu_437_p4);
    sensitive << ( dpValues_q0 );

    SC_METHOD(thread_r_V_fu_507_p2);
    sensitive << ( r_V_6_fu_487_p2 );
    sensitive << ( r_V_8_fu_503_p1 );

    SC_METHOD(thread_sum_o);
    sensitive << ( sum_i );
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_8_fu_536_p2 );
    sensitive << ( v_V_21_fu_424_p2 );
    sensitive << ( v_V_15_fu_480_p2 );
    sensitive << ( ap_condition_171 );

    SC_METHOD(thread_sum_o_ap_vld);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_8_fu_536_p2 );
    sensitive << ( tmp_7_fu_542_p2 );

    SC_METHOD(thread_temp_o);
    sensitive << ( temp_i );
    sensitive << ( keys_q0 );
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_temp_o_ap_vld);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_10_fu_415_p1);
    sensitive << ( sum_i );

    SC_METHOD(thread_tmp_12_fu_519_p1);
    sensitive << ( sum_i );

    SC_METHOD(thread_tmp_14_fu_463_p1);
    sensitive << ( sum_i );

    SC_METHOD(thread_tmp_2_fu_523_p2);
    sensitive << ( temp_i );
    sensitive << ( tmp_12_fu_519_p1 );

    SC_METHOD(thread_tmp_3_fu_410_p1);
    sensitive << ( p_Result_1_fu_400_p4 );

    SC_METHOD(thread_tmp_4_fu_457_p2);
    sensitive << ( dpValues_q0 );
    sensitive << ( r_V_4_fu_451_p2 );

    SC_METHOD(thread_tmp_6_fu_467_p2);
    sensitive << ( temp_i );
    sensitive << ( tmp_14_fu_463_p1 );

    SC_METHOD(thread_tmp_7_fu_542_p2);
    sensitive << ( command );
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_8_fu_536_p2 );

    SC_METHOD(thread_tmp_8_fu_536_p2);
    sensitive << ( command );
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_9_fu_419_p1);
    sensitive << ( tmp_10_fu_415_p1 );

    SC_METHOD(thread_tmp_read_fu_144_p2);
    sensitive << ( fsmState );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_tmp_s_fu_513_p2);
    sensitive << ( dpValues_q0 );
    sensitive << ( r_V_fu_507_p2 );

    SC_METHOD(thread_v_V_13_fu_529_p2);
    sensitive << ( tmp_s_fu_513_p2 );
    sensitive << ( tmp_2_fu_523_p2 );

    SC_METHOD(thread_v_V_15_fu_480_p2);
    sensitive << ( sum_i );

    SC_METHOD(thread_v_V_17_fu_473_p2);
    sensitive << ( tmp_4_fu_457_p2 );
    sensitive << ( tmp_6_fu_467_p2 );

    SC_METHOD(thread_v_V_21_fu_424_p2);
    sensitive << ( sum_i );

    SC_METHOD(thread_values_address0);
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_values_address1);
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_values_ce0);
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_values_ce1);
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_xtea_dpValues_Val_V_10_gep_fu_337_p3);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_xtea_dpValues_Val_V_12_gep_fu_328_p3);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_xtea_dpValues_Val_V_14_gep_fu_319_p3);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_xtea_dpValues_Val_V_5_gep_fu_275_p3);
    sensitive << ( tmp_read_fu_144_p2 );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_xtea_dpValues_Val_V_6_gep_fu_266_p3);
    sensitive << ( tmp_read_fu_144_p2 );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_xtea_dpValues_Val_V_7_gep_fu_346_p3);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_xtea_dpValues_Val_V_8_gep_fu_243_p3);
    sensitive << ( tmp_read_fu_144_p2 );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_xtea_dpValues_Val_V_9_gep_fu_234_p3);
    sensitive << ( tmp_read_fu_144_p2 );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_xtea_dpValues_Val_V_s_gep_fu_355_p3);
    sensitive << ( tmp_reg_548 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "xtea_datapath_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, counter_i, "(port)counter_i");
    sc_trace(mVcdFile, counter_o, "(port)counter_o");
    sc_trace(mVcdFile, counter_o_ap_vld, "(port)counter_o_ap_vld");
    sc_trace(mVcdFile, sum_i, "(port)sum_i");
    sc_trace(mVcdFile, sum_o, "(port)sum_o");
    sc_trace(mVcdFile, sum_o_ap_vld, "(port)sum_o_ap_vld");
    sc_trace(mVcdFile, temp_i, "(port)temp_i");
    sc_trace(mVcdFile, temp_o, "(port)temp_o");
    sc_trace(mVcdFile, temp_o_ap_vld, "(port)temp_o_ap_vld");
    sc_trace(mVcdFile, acc_i, "(port)acc_i");
    sc_trace(mVcdFile, acc_o, "(port)acc_o");
    sc_trace(mVcdFile, acc_o_ap_vld, "(port)acc_o_ap_vld");
    sc_trace(mVcdFile, dpValues_address0, "(port)dpValues_address0");
    sc_trace(mVcdFile, dpValues_ce0, "(port)dpValues_ce0");
    sc_trace(mVcdFile, dpValues_we0, "(port)dpValues_we0");
    sc_trace(mVcdFile, dpValues_d0, "(port)dpValues_d0");
    sc_trace(mVcdFile, dpValues_q0, "(port)dpValues_q0");
    sc_trace(mVcdFile, dpValues_address1, "(port)dpValues_address1");
    sc_trace(mVcdFile, dpValues_ce1, "(port)dpValues_ce1");
    sc_trace(mVcdFile, dpValues_we1, "(port)dpValues_we1");
    sc_trace(mVcdFile, dpValues_d1, "(port)dpValues_d1");
    sc_trace(mVcdFile, keys_address0, "(port)keys_address0");
    sc_trace(mVcdFile, keys_ce0, "(port)keys_ce0");
    sc_trace(mVcdFile, keys_q0, "(port)keys_q0");
    sc_trace(mVcdFile, values_address0, "(port)values_address0");
    sc_trace(mVcdFile, values_ce0, "(port)values_ce0");
    sc_trace(mVcdFile, values_q0, "(port)values_q0");
    sc_trace(mVcdFile, values_address1, "(port)values_address1");
    sc_trace(mVcdFile, values_ce1, "(port)values_ce1");
    sc_trace(mVcdFile, values_q1, "(port)values_q1");
    sc_trace(mVcdFile, fsmState, "(port)fsmState");
    sc_trace(mVcdFile, command, "(port)command");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, tmp_read_fu_144_p2, "tmp_read_fu_144_p2");
    sc_trace(mVcdFile, tmp_reg_548, "tmp_reg_548");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, xtea_dpValues_Val_V_9_gep_fu_234_p3, "xtea_dpValues_Val_V_9_gep_fu_234_p3");
    sc_trace(mVcdFile, xtea_dpValues_Val_V_8_gep_fu_243_p3, "xtea_dpValues_Val_V_8_gep_fu_243_p3");
    sc_trace(mVcdFile, xtea_dpValues_Val_V_6_gep_fu_266_p3, "xtea_dpValues_Val_V_6_gep_fu_266_p3");
    sc_trace(mVcdFile, xtea_dpValues_Val_V_5_gep_fu_275_p3, "xtea_dpValues_Val_V_5_gep_fu_275_p3");
    sc_trace(mVcdFile, tmp_3_fu_410_p1, "tmp_3_fu_410_p1");
    sc_trace(mVcdFile, tmp_9_fu_419_p1, "tmp_9_fu_419_p1");
    sc_trace(mVcdFile, xtea_dpValues_Val_V_14_gep_fu_319_p3, "xtea_dpValues_Val_V_14_gep_fu_319_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, xtea_dpValues_Val_V_12_gep_fu_328_p3, "xtea_dpValues_Val_V_12_gep_fu_328_p3");
    sc_trace(mVcdFile, xtea_dpValues_Val_V_10_gep_fu_337_p3, "xtea_dpValues_Val_V_10_gep_fu_337_p3");
    sc_trace(mVcdFile, xtea_dpValues_Val_V_7_gep_fu_346_p3, "xtea_dpValues_Val_V_7_gep_fu_346_p3");
    sc_trace(mVcdFile, xtea_dpValues_Val_V_s_gep_fu_355_p3, "xtea_dpValues_Val_V_s_gep_fu_355_p3");
    sc_trace(mVcdFile, grp_fu_386_p2, "grp_fu_386_p2");
    sc_trace(mVcdFile, tmp_8_fu_536_p2, "tmp_8_fu_536_p2");
    sc_trace(mVcdFile, tmp_7_fu_542_p2, "tmp_7_fu_542_p2");
    sc_trace(mVcdFile, v_V_21_fu_424_p2, "v_V_21_fu_424_p2");
    sc_trace(mVcdFile, v_V_15_fu_480_p2, "v_V_15_fu_480_p2");
    sc_trace(mVcdFile, v_V_17_fu_473_p2, "v_V_17_fu_473_p2");
    sc_trace(mVcdFile, v_V_13_fu_529_p2, "v_V_13_fu_529_p2");
    sc_trace(mVcdFile, grp_fu_379_p2, "grp_fu_379_p2");
    sc_trace(mVcdFile, grp_fu_393_p2, "grp_fu_393_p2");
    sc_trace(mVcdFile, p_Result_1_fu_400_p4, "p_Result_1_fu_400_p4");
    sc_trace(mVcdFile, tmp_10_fu_415_p1, "tmp_10_fu_415_p1");
    sc_trace(mVcdFile, r_V_9_fu_437_p4, "r_V_9_fu_437_p4");
    sc_trace(mVcdFile, r_V_10_fu_431_p2, "r_V_10_fu_431_p2");
    sc_trace(mVcdFile, r_V_11_fu_447_p1, "r_V_11_fu_447_p1");
    sc_trace(mVcdFile, r_V_4_fu_451_p2, "r_V_4_fu_451_p2");
    sc_trace(mVcdFile, tmp_14_fu_463_p1, "tmp_14_fu_463_p1");
    sc_trace(mVcdFile, tmp_4_fu_457_p2, "tmp_4_fu_457_p2");
    sc_trace(mVcdFile, tmp_6_fu_467_p2, "tmp_6_fu_467_p2");
    sc_trace(mVcdFile, r_V_7_fu_493_p4, "r_V_7_fu_493_p4");
    sc_trace(mVcdFile, r_V_6_fu_487_p2, "r_V_6_fu_487_p2");
    sc_trace(mVcdFile, r_V_8_fu_503_p1, "r_V_8_fu_503_p1");
    sc_trace(mVcdFile, r_V_fu_507_p2, "r_V_fu_507_p2");
    sc_trace(mVcdFile, tmp_12_fu_519_p1, "tmp_12_fu_519_p1");
    sc_trace(mVcdFile, tmp_s_fu_513_p2, "tmp_s_fu_513_p2");
    sc_trace(mVcdFile, tmp_2_fu_523_p2, "tmp_2_fu_523_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_171, "ap_condition_171");
#endif

    }
}

xtea_datapath::~xtea_datapath() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void xtea_datapath::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        tmp_reg_548 = fsmState.read();
    }
}

void xtea_datapath::thread_acc_o() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if ((esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_D) || 
             esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_5))) {
            acc_o = v_V_13_fu_529_p2.read();
        } else if ((esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_A) || 
                    esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_8))) {
            acc_o = v_V_17_fu_473_p2.read();
        } else {
            acc_o = acc_i.read();
        }
    } else {
        acc_o = acc_i.read();
    }
}

void xtea_datapath::thread_acc_o_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          (esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_A) || 
           esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_8))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          (esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_D) || 
           esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_5))))) {
        acc_o_ap_vld = ap_const_logic_1;
    } else {
        acc_o_ap_vld = ap_const_logic_0;
    }
}

void xtea_datapath::thread_ap_CS_fsm() {
    ap_CS_fsm = ap_ST_fsm_state1;
}

void xtea_datapath::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_ST_fsm_state1[0];
}

void xtea_datapath::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_ST_fsm_state1[1];
}

void xtea_datapath::thread_ap_condition_171() {
    ap_condition_171 = (esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1) && esl_seteq<1,1,1>(tmp_8_fu_536_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_7_fu_542_p2.read(), ap_const_lv1_1));
}

void xtea_datapath::thread_counter_o() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1) && 
          esl_seteq<1,1,1>(tmp_8_fu_536_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_7_fu_542_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1) && 
          esl_seteq<1,1,1>(tmp_8_fu_536_p2.read(), ap_const_lv1_1)))) {
        counter_o = ap_const_lv6_0;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                 esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_E)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                 esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_9)))) {
        counter_o = grp_fu_386_p2.read();
    } else {
        counter_o = counter_i.read();
    }
}

void xtea_datapath::thread_counter_o_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_E)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_9)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1) && 
          esl_seteq<1,1,1>(tmp_8_fu_536_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_7_fu_542_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1) && 
          esl_seteq<1,1,1>(tmp_8_fu_536_p2.read(), ap_const_lv1_1)))) {
        counter_o_ap_vld = ap_const_logic_1;
    } else {
        counter_o_ap_vld = ap_const_logic_0;
    }
}

void xtea_datapath::thread_dpValues_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1))) {
        dpValues_address0 = xtea_dpValues_Val_V_s_gep_fu_355_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_6))) {
        dpValues_address0 = xtea_dpValues_Val_V_7_gep_fu_346_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_9))) {
        dpValues_address0 = xtea_dpValues_Val_V_10_gep_fu_337_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_B))) {
        dpValues_address0 = xtea_dpValues_Val_V_12_gep_fu_328_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_E))) {
        dpValues_address0 = xtea_dpValues_Val_V_14_gep_fu_319_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                (esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_D) || 
                 esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_5)))) {
        dpValues_address0 = xtea_dpValues_Val_V_5_gep_fu_275_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_6))) {
        dpValues_address0 = xtea_dpValues_Val_V_6_gep_fu_266_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                (esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_A) || 
                 esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_8)))) {
        dpValues_address0 = xtea_dpValues_Val_V_8_gep_fu_243_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_9))) {
        dpValues_address0 = xtea_dpValues_Val_V_9_gep_fu_234_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_B))) {
        dpValues_address0 =  (sc_lv<1>) (ap_const_lv64_1);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_E))) {
        dpValues_address0 =  (sc_lv<1>) (ap_const_lv64_0);
    } else {
        dpValues_address0 = "X";
    }
}

void xtea_datapath::thread_dpValues_address1() {
    dpValues_address1 =  (sc_lv<1>) (ap_const_lv64_1);
}

void xtea_datapath::thread_dpValues_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_E)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_B)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_9)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          (esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_A) || 
           esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_8))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_6)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          (esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_D) || 
           esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_5))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_E)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_B)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_9)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_6)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1)))) {
        dpValues_ce0 = ap_const_logic_1;
    } else {
        dpValues_ce0 = ap_const_logic_0;
    }
}

void xtea_datapath::thread_dpValues_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        dpValues_ce1 = ap_const_logic_1;
    } else {
        dpValues_ce1 = ap_const_logic_0;
    }
}

void xtea_datapath::thread_dpValues_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1))) {
        dpValues_d0 = values_q0.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                 esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_9)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                 esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_6)))) {
        dpValues_d0 = grp_fu_393_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                 esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_E)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                 esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_B)))) {
        dpValues_d0 = grp_fu_379_p2.read();
    } else {
        dpValues_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void xtea_datapath::thread_dpValues_d1() {
    dpValues_d1 = values_q1.read();
}

void xtea_datapath::thread_dpValues_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_E)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_B)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_9)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_6)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1)))) {
        dpValues_we0 = ap_const_logic_1;
    } else {
        dpValues_we0 = ap_const_logic_0;
    }
}

void xtea_datapath::thread_dpValues_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1))) {
        dpValues_we1 = ap_const_logic_1;
    } else {
        dpValues_we1 = ap_const_logic_0;
    }
}

void xtea_datapath::thread_grp_fu_379_p2() {
    grp_fu_379_p2 = (!dpValues_q0.read().is_01() || !acc_i.read().is_01())? sc_lv<32>(): (sc_biguint<32>(dpValues_q0.read()) - sc_biguint<32>(acc_i.read()));
}

void xtea_datapath::thread_grp_fu_386_p2() {
    grp_fu_386_p2 = (!counter_i.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(counter_i.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void xtea_datapath::thread_grp_fu_393_p2() {
    grp_fu_393_p2 = (!acc_i.read().is_01() || !dpValues_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(acc_i.read()) + sc_biguint<32>(dpValues_q0.read()));
}

void xtea_datapath::thread_keys_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        if ((esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_C) || 
             esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_3))) {
            keys_address0 =  (sc_lv<2>) (tmp_9_fu_419_p1.read());
        } else if ((esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_4) || 
                    esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_7))) {
            keys_address0 =  (sc_lv<2>) (tmp_3_fu_410_p1.read());
        } else {
            keys_address0 =  (sc_lv<2>) ("XX");
        }
    } else {
        keys_address0 =  (sc_lv<2>) ("XX");
    }
}

void xtea_datapath::thread_keys_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          (esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_4) || 
           esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_7))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          (esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_C) || 
           esl_seteq<1,32,32>(tmp_read_fu_144_p2.read(), ap_const_lv32_3))))) {
        keys_ce0 = ap_const_logic_1;
    } else {
        keys_ce0 = ap_const_logic_0;
    }
}

void xtea_datapath::thread_p_Result_1_fu_400_p4() {
    p_Result_1_fu_400_p4 = sum_i.read().range(12, 11);
}

void xtea_datapath::thread_r_V_10_fu_431_p2() {
    r_V_10_fu_431_p2 = (!ap_const_lv32_4.is_01())? sc_lv<32>(): dpValues_q0.read() << (unsigned short)ap_const_lv32_4.to_uint();
}

void xtea_datapath::thread_r_V_11_fu_447_p1() {
    r_V_11_fu_447_p1 = esl_zext<32,27>(r_V_9_fu_437_p4.read());
}

void xtea_datapath::thread_r_V_4_fu_451_p2() {
    r_V_4_fu_451_p2 = (r_V_10_fu_431_p2.read() ^ r_V_11_fu_447_p1.read());
}

void xtea_datapath::thread_r_V_6_fu_487_p2() {
    r_V_6_fu_487_p2 = (!ap_const_lv32_4.is_01())? sc_lv<32>(): dpValues_q0.read() << (unsigned short)ap_const_lv32_4.to_uint();
}

void xtea_datapath::thread_r_V_7_fu_493_p4() {
    r_V_7_fu_493_p4 = dpValues_q0.read().range(31, 5);
}

void xtea_datapath::thread_r_V_8_fu_503_p1() {
    r_V_8_fu_503_p1 = esl_zext<32,27>(r_V_7_fu_493_p4.read());
}

void xtea_datapath::thread_r_V_9_fu_437_p4() {
    r_V_9_fu_437_p4 = dpValues_q0.read().range(31, 5);
}

void xtea_datapath::thread_r_V_fu_507_p2() {
    r_V_fu_507_p2 = (r_V_6_fu_487_p2.read() ^ r_V_8_fu_503_p1.read());
}

void xtea_datapath::thread_sum_o() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if ((esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1) && 
             esl_seteq<1,1,1>(tmp_8_fu_536_p2.read(), ap_const_lv1_1))) {
            sum_o = ap_const_lv64_0;
        } else if (esl_seteq<1,1,1>(ap_condition_171.read(), ap_const_boolean_1)) {
            sum_o = ap_const_lv64_C6EF3720;
        } else if (esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_6)) {
            sum_o = v_V_15_fu_480_p2.read();
        } else if (esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_B)) {
            sum_o = v_V_21_fu_424_p2.read();
        } else {
            sum_o = sum_i.read();
        }
    } else {
        sum_o = sum_i.read();
    }
}

void xtea_datapath::thread_sum_o_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_B)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_6)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1) && 
          esl_seteq<1,1,1>(tmp_8_fu_536_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_7_fu_542_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_1) && 
          esl_seteq<1,1,1>(tmp_8_fu_536_p2.read(), ap_const_lv1_1)))) {
        sum_o_ap_vld = ap_const_logic_1;
    } else {
        sum_o_ap_vld = ap_const_logic_0;
    }
}

void xtea_datapath::thread_temp_o() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          (esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_4) || 
           esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_7))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          (esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_C) || 
           esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_3))))) {
        temp_o = keys_q0.read();
    } else {
        temp_o = temp_i.read();
    }
}

void xtea_datapath::thread_temp_o_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          (esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_4) || 
           esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_7))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          (esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_C) || 
           esl_seteq<1,32,32>(tmp_reg_548.read(), ap_const_lv32_3))))) {
        temp_o_ap_vld = ap_const_logic_1;
    } else {
        temp_o_ap_vld = ap_const_logic_0;
    }
}

void xtea_datapath::thread_tmp_10_fu_415_p1() {
    tmp_10_fu_415_p1 = sum_i.read().range(2-1, 0);
}

void xtea_datapath::thread_tmp_12_fu_519_p1() {
    tmp_12_fu_519_p1 = sum_i.read().range(32-1, 0);
}

void xtea_datapath::thread_tmp_14_fu_463_p1() {
    tmp_14_fu_463_p1 = sum_i.read().range(32-1, 0);
}

void xtea_datapath::thread_tmp_2_fu_523_p2() {
    tmp_2_fu_523_p2 = (!tmp_12_fu_519_p1.read().is_01() || !temp_i.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_12_fu_519_p1.read()) + sc_biguint<32>(temp_i.read()));
}

void xtea_datapath::thread_tmp_3_fu_410_p1() {
    tmp_3_fu_410_p1 = esl_zext<64,2>(p_Result_1_fu_400_p4.read());
}

void xtea_datapath::thread_tmp_4_fu_457_p2() {
    tmp_4_fu_457_p2 = (!r_V_4_fu_451_p2.read().is_01() || !dpValues_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(r_V_4_fu_451_p2.read()) + sc_biguint<32>(dpValues_q0.read()));
}

void xtea_datapath::thread_tmp_6_fu_467_p2() {
    tmp_6_fu_467_p2 = (!tmp_14_fu_463_p1.read().is_01() || !temp_i.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_14_fu_463_p1.read()) + sc_biguint<32>(temp_i.read()));
}

void xtea_datapath::thread_tmp_7_fu_542_p2() {
    tmp_7_fu_542_p2 = (!command.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(command.read() == ap_const_lv2_3);
}

void xtea_datapath::thread_tmp_8_fu_536_p2() {
    tmp_8_fu_536_p2 = (!command.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(command.read() == ap_const_lv2_2);
}

void xtea_datapath::thread_tmp_9_fu_419_p1() {
    tmp_9_fu_419_p1 = esl_zext<64,2>(tmp_10_fu_415_p1.read());
}

void xtea_datapath::thread_tmp_read_fu_144_p2() {
    tmp_read_fu_144_p2 = fsmState.read();
}

void xtea_datapath::thread_tmp_s_fu_513_p2() {
    tmp_s_fu_513_p2 = (!r_V_fu_507_p2.read().is_01() || !dpValues_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(r_V_fu_507_p2.read()) + sc_biguint<32>(dpValues_q0.read()));
}

void xtea_datapath::thread_v_V_13_fu_529_p2() {
    v_V_13_fu_529_p2 = (tmp_s_fu_513_p2.read() ^ tmp_2_fu_523_p2.read());
}

void xtea_datapath::thread_v_V_15_fu_480_p2() {
    v_V_15_fu_480_p2 = (!sum_i.read().is_01() || !ap_const_lv64_9E3779B9.is_01())? sc_lv<64>(): (sc_biguint<64>(sum_i.read()) + sc_biguint<64>(ap_const_lv64_9E3779B9));
}

void xtea_datapath::thread_v_V_17_fu_473_p2() {
    v_V_17_fu_473_p2 = (tmp_4_fu_457_p2.read() ^ tmp_6_fu_467_p2.read());
}

void xtea_datapath::thread_v_V_21_fu_424_p2() {
    v_V_21_fu_424_p2 = (!sum_i.read().is_01() || !ap_const_lv64_FFFFFFFF61C88647.is_01())? sc_lv<64>(): (sc_biguint<64>(sum_i.read()) + sc_bigint<64>(ap_const_lv64_FFFFFFFF61C88647));
}

void xtea_datapath::thread_values_address0() {
    values_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void xtea_datapath::thread_values_address1() {
    values_address1 =  (sc_lv<1>) (ap_const_lv64_1);
}

void xtea_datapath::thread_values_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        values_ce0 = ap_const_logic_1;
    } else {
        values_ce0 = ap_const_logic_0;
    }
}

void xtea_datapath::thread_values_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        values_ce1 = ap_const_logic_1;
    } else {
        values_ce1 = ap_const_logic_0;
    }
}

void xtea_datapath::thread_xtea_dpValues_Val_V_10_gep_fu_337_p3() {
    xtea_dpValues_Val_V_10_gep_fu_337_p3 =  (sc_lv<1>) (ap_const_lv64_1);
}

void xtea_datapath::thread_xtea_dpValues_Val_V_12_gep_fu_328_p3() {
    xtea_dpValues_Val_V_12_gep_fu_328_p3 =  (sc_lv<1>) (ap_const_lv64_1);
}

void xtea_datapath::thread_xtea_dpValues_Val_V_14_gep_fu_319_p3() {
    xtea_dpValues_Val_V_14_gep_fu_319_p3 =  (sc_lv<1>) (ap_const_lv64_0);
}

void xtea_datapath::thread_xtea_dpValues_Val_V_5_gep_fu_275_p3() {
    xtea_dpValues_Val_V_5_gep_fu_275_p3 =  (sc_lv<1>) (ap_const_lv64_1);
}

void xtea_datapath::thread_xtea_dpValues_Val_V_6_gep_fu_266_p3() {
    xtea_dpValues_Val_V_6_gep_fu_266_p3 =  (sc_lv<1>) (ap_const_lv64_0);
}

void xtea_datapath::thread_xtea_dpValues_Val_V_7_gep_fu_346_p3() {
    xtea_dpValues_Val_V_7_gep_fu_346_p3 =  (sc_lv<1>) (ap_const_lv64_0);
}

void xtea_datapath::thread_xtea_dpValues_Val_V_8_gep_fu_243_p3() {
    xtea_dpValues_Val_V_8_gep_fu_243_p3 =  (sc_lv<1>) (ap_const_lv64_0);
}

void xtea_datapath::thread_xtea_dpValues_Val_V_9_gep_fu_234_p3() {
    xtea_dpValues_Val_V_9_gep_fu_234_p3 =  (sc_lv<1>) (ap_const_lv64_1);
}

void xtea_datapath::thread_xtea_dpValues_Val_V_s_gep_fu_355_p3() {
    xtea_dpValues_Val_V_s_gep_fu_355_p3 =  (sc_lv<1>) (ap_const_lv64_0);
}

void xtea_datapath::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

}

