// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module xtea_datapath (
        ap_clk,
        ap_rst,
        counter_i,
        counter_o,
        counter_o_ap_vld,
        sum_i,
        sum_o,
        sum_o_ap_vld,
        temp_i,
        temp_o,
        temp_o_ap_vld,
        acc_i,
        acc_o,
        acc_o_ap_vld,
        dpValues_address0,
        dpValues_ce0,
        dpValues_we0,
        dpValues_d0,
        dpValues_q0,
        dpValues_address1,
        dpValues_ce1,
        dpValues_we1,
        dpValues_d1,
        keys_address0,
        keys_ce0,
        keys_q0,
        values_address0,
        values_ce0,
        values_q0,
        values_address1,
        values_ce1,
        values_q1,
        fsmState,
        command
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;



input   ap_clk;
input   ap_rst;
input  [5:0] counter_i;
output  [5:0] counter_o;
output   counter_o_ap_vld;
input  [63:0] sum_i;
output  [63:0] sum_o;
output   sum_o_ap_vld;
input  [31:0] temp_i;
output  [31:0] temp_o;
output   temp_o_ap_vld;
input  [31:0] acc_i;
output  [31:0] acc_o;
output   acc_o_ap_vld;
output  [0:0] dpValues_address0;
output   dpValues_ce0;
output   dpValues_we0;
output  [31:0] dpValues_d0;
input  [31:0] dpValues_q0;
output  [0:0] dpValues_address1;
output   dpValues_ce1;
output   dpValues_we1;
output  [31:0] dpValues_d1;
output  [1:0] keys_address0;
output   keys_ce0;
input  [31:0] keys_q0;
output  [0:0] values_address0;
output   values_ce0;
input  [31:0] values_q0;
output  [0:0] values_address1;
output   values_ce1;
input  [31:0] values_q1;
input  [31:0] fsmState;
input  [1:0] command;

reg[5:0] counter_o;
reg counter_o_ap_vld;
reg[63:0] sum_o;
reg sum_o_ap_vld;
reg[31:0] temp_o;
reg temp_o_ap_vld;
reg[31:0] acc_o;
reg acc_o_ap_vld;
reg[0:0] dpValues_address0;
reg dpValues_ce0;
reg dpValues_we0;
reg[31:0] dpValues_d0;
reg dpValues_ce1;
reg dpValues_we1;
reg[1:0] keys_address0;
reg keys_ce0;
reg values_ce0;
reg values_ce1;

wire   [31:0] tmp_read_fu_144_p2;
reg   [31:0] tmp_reg_548;
wire   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] xtea_dpValues_Val_V_9_gep_fu_234_p3;
wire   [0:0] xtea_dpValues_Val_V_8_gep_fu_243_p3;
wire   [0:0] xtea_dpValues_Val_V_6_gep_fu_266_p3;
wire   [0:0] xtea_dpValues_Val_V_5_gep_fu_275_p3;
wire   [63:0] tmp_3_fu_410_p1;
wire   [63:0] tmp_9_fu_419_p1;
wire   [0:0] xtea_dpValues_Val_V_14_gep_fu_319_p3;
wire    ap_CS_fsm_state2;
wire   [0:0] xtea_dpValues_Val_V_12_gep_fu_328_p3;
wire   [0:0] xtea_dpValues_Val_V_10_gep_fu_337_p3;
wire   [0:0] xtea_dpValues_Val_V_7_gep_fu_346_p3;
wire   [0:0] xtea_dpValues_Val_V_s_gep_fu_355_p3;
wire   [5:0] grp_fu_386_p2;
wire   [0:0] tmp_8_fu_536_p2;
wire   [0:0] tmp_7_fu_542_p2;
wire   [63:0] v_V_21_fu_424_p2;
wire   [63:0] v_V_15_fu_480_p2;
wire   [31:0] v_V_17_fu_473_p2;
wire   [31:0] v_V_13_fu_529_p2;
wire   [31:0] grp_fu_379_p2;
wire   [31:0] grp_fu_393_p2;
wire   [1:0] p_Result_1_fu_400_p4;
wire   [1:0] tmp_10_fu_415_p1;
wire   [26:0] r_V_9_fu_437_p4;
wire   [31:0] r_V_10_fu_431_p2;
wire   [31:0] r_V_11_fu_447_p1;
wire   [31:0] r_V_4_fu_451_p2;
wire   [31:0] tmp_14_fu_463_p1;
wire   [31:0] tmp_4_fu_457_p2;
wire   [31:0] tmp_6_fu_467_p2;
wire   [26:0] r_V_7_fu_493_p4;
wire   [31:0] r_V_6_fu_487_p2;
wire   [31:0] r_V_8_fu_503_p1;
wire   [31:0] r_V_fu_507_p2;
wire   [31:0] tmp_12_fu_519_p1;
wire   [31:0] tmp_s_fu_513_p2;
wire   [31:0] tmp_2_fu_523_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_condition_171;

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_reg_548 <= fsmState;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if (((tmp_reg_548 == 32'd5) | (tmp_reg_548 == 32'd13))) begin
            acc_o = v_V_13_fu_529_p2;
        end else if (((tmp_reg_548 == 32'd8) | (tmp_reg_548 == 32'd10))) begin
            acc_o = v_V_17_fu_473_p2;
        end else begin
            acc_o = acc_i;
        end
    end else begin
        acc_o = acc_i;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & ((tmp_reg_548 == 32'd5) | (tmp_reg_548 == 32'd13))) | ((1'b1 == ap_CS_fsm_state2) & ((tmp_reg_548 == 32'd8) | (tmp_reg_548 == 32'd10))))) begin
        acc_o_ap_vld = 1'b1;
    end else begin
        acc_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_8_fu_536_p2 == 1'd1)) | ((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_7_fu_542_p2 == 1'd1) & (tmp_8_fu_536_p2 == 1'd0)))) begin
        counter_o = 6'd0;
    end else if ((((tmp_reg_548 == 32'd9) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd14) & (1'b1 == ap_CS_fsm_state2)))) begin
        counter_o = grp_fu_386_p2;
    end else begin
        counter_o = counter_i;
    end
end

always @ (*) begin
    if ((((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_8_fu_536_p2 == 1'd1)) | ((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_7_fu_542_p2 == 1'd1) & (tmp_8_fu_536_p2 == 1'd0)) | ((tmp_reg_548 == 32'd9) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd14) & (1'b1 == ap_CS_fsm_state2)))) begin
        counter_o_ap_vld = 1'b1;
    end else begin
        counter_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        dpValues_address0 = xtea_dpValues_Val_V_s_gep_fu_355_p3;
    end else if (((tmp_reg_548 == 32'd6) & (1'b1 == ap_CS_fsm_state2))) begin
        dpValues_address0 = xtea_dpValues_Val_V_7_gep_fu_346_p3;
    end else if (((tmp_reg_548 == 32'd9) & (1'b1 == ap_CS_fsm_state2))) begin
        dpValues_address0 = xtea_dpValues_Val_V_10_gep_fu_337_p3;
    end else if (((tmp_reg_548 == 32'd11) & (1'b1 == ap_CS_fsm_state2))) begin
        dpValues_address0 = xtea_dpValues_Val_V_12_gep_fu_328_p3;
    end else if (((tmp_reg_548 == 32'd14) & (1'b1 == ap_CS_fsm_state2))) begin
        dpValues_address0 = xtea_dpValues_Val_V_14_gep_fu_319_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & ((tmp_read_fu_144_p2 == 32'd5) | (tmp_read_fu_144_p2 == 32'd13)))) begin
        dpValues_address0 = xtea_dpValues_Val_V_5_gep_fu_275_p3;
    end else if (((tmp_read_fu_144_p2 == 32'd6) & (1'b1 == ap_CS_fsm_state1))) begin
        dpValues_address0 = xtea_dpValues_Val_V_6_gep_fu_266_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & ((tmp_read_fu_144_p2 == 32'd8) | (tmp_read_fu_144_p2 == 32'd10)))) begin
        dpValues_address0 = xtea_dpValues_Val_V_8_gep_fu_243_p3;
    end else if (((tmp_read_fu_144_p2 == 32'd9) & (1'b1 == ap_CS_fsm_state1))) begin
        dpValues_address0 = xtea_dpValues_Val_V_9_gep_fu_234_p3;
    end else if (((tmp_read_fu_144_p2 == 32'd11) & (1'b1 == ap_CS_fsm_state1))) begin
        dpValues_address0 = 64'd1;
    end else if (((tmp_read_fu_144_p2 == 32'd14) & (1'b1 == ap_CS_fsm_state1))) begin
        dpValues_address0 = 64'd0;
    end else begin
        dpValues_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_read_fu_144_p2 == 32'd6) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state1) & ((tmp_read_fu_144_p2 == 32'd8) | (tmp_read_fu_144_p2 == 32'd10))) | ((tmp_read_fu_144_p2 == 32'd9) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_read_fu_144_p2 == 32'd11) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_read_fu_144_p2 == 32'd14) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state1) & ((tmp_read_fu_144_p2 == 32'd5) | (tmp_read_fu_144_p2 == 32'd13))) | ((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd6) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd9) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd11) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd14) & (1'b1 == ap_CS_fsm_state2)))) begin
        dpValues_ce0 = 1'b1;
    end else begin
        dpValues_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        dpValues_ce1 = 1'b1;
    end else begin
        dpValues_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        dpValues_d0 = values_q0;
    end else if ((((tmp_reg_548 == 32'd6) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd9) & (1'b1 == ap_CS_fsm_state2)))) begin
        dpValues_d0 = grp_fu_393_p2;
    end else if ((((tmp_reg_548 == 32'd11) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd14) & (1'b1 == ap_CS_fsm_state2)))) begin
        dpValues_d0 = grp_fu_379_p2;
    end else begin
        dpValues_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd6) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd9) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd11) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd14) & (1'b1 == ap_CS_fsm_state2)))) begin
        dpValues_we0 = 1'b1;
    end else begin
        dpValues_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        dpValues_we1 = 1'b1;
    end else begin
        dpValues_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((tmp_read_fu_144_p2 == 32'd3) | (tmp_read_fu_144_p2 == 32'd12))) begin
            keys_address0 = tmp_9_fu_419_p1;
        end else if (((tmp_read_fu_144_p2 == 32'd7) | (tmp_read_fu_144_p2 == 32'd4))) begin
            keys_address0 = tmp_3_fu_410_p1;
        end else begin
            keys_address0 = 'bx;
        end
    end else begin
        keys_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & ((tmp_read_fu_144_p2 == 32'd7) | (tmp_read_fu_144_p2 == 32'd4))) | ((1'b1 == ap_CS_fsm_state1) & ((tmp_read_fu_144_p2 == 32'd3) | (tmp_read_fu_144_p2 == 32'd12))))) begin
        keys_ce0 = 1'b1;
    end else begin
        keys_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if (((tmp_reg_548 == 32'd1) & (tmp_8_fu_536_p2 == 1'd1))) begin
            sum_o = 64'd0;
        end else if ((1'b1 == ap_condition_171)) begin
            sum_o = 64'd3337565984;
        end else if ((tmp_reg_548 == 32'd6)) begin
            sum_o = v_V_15_fu_480_p2;
        end else if ((tmp_reg_548 == 32'd11)) begin
            sum_o = v_V_21_fu_424_p2;
        end else begin
            sum_o = sum_i;
        end
    end else begin
        sum_o = sum_i;
    end
end

always @ (*) begin
    if ((((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_8_fu_536_p2 == 1'd1)) | ((tmp_reg_548 == 32'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_7_fu_542_p2 == 1'd1) & (tmp_8_fu_536_p2 == 1'd0)) | ((tmp_reg_548 == 32'd6) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_reg_548 == 32'd11) & (1'b1 == ap_CS_fsm_state2)))) begin
        sum_o_ap_vld = 1'b1;
    end else begin
        sum_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & ((tmp_reg_548 == 32'd3) | (tmp_reg_548 == 32'd12))) | ((1'b1 == ap_CS_fsm_state2) & ((tmp_reg_548 == 32'd7) | (tmp_reg_548 == 32'd4))))) begin
        temp_o = keys_q0;
    end else begin
        temp_o = temp_i;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & ((tmp_reg_548 == 32'd3) | (tmp_reg_548 == 32'd12))) | ((1'b1 == ap_CS_fsm_state2) & ((tmp_reg_548 == 32'd7) | (tmp_reg_548 == 32'd4))))) begin
        temp_o_ap_vld = 1'b1;
    end else begin
        temp_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        values_ce0 = 1'b1;
    end else begin
        values_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        values_ce1 = 1'b1;
    end else begin
        values_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm = ap_ST_fsm_state1;

assign ap_CS_fsm_state1 = ap_ST_fsm_state1[32'd0];

assign ap_CS_fsm_state2 = ap_ST_fsm_state1[32'd1];

always @ (*) begin
    ap_condition_171 = ((tmp_reg_548 == 32'd1) & (tmp_7_fu_542_p2 == 1'd1) & (tmp_8_fu_536_p2 == 1'd0));
end

assign dpValues_address1 = 64'd1;

assign dpValues_d1 = values_q1;

assign grp_fu_379_p2 = (dpValues_q0 - acc_i);

assign grp_fu_386_p2 = (counter_i + 6'd1);

assign grp_fu_393_p2 = (acc_i + dpValues_q0);

assign p_Result_1_fu_400_p4 = {{sum_i[12:11]}};

assign r_V_10_fu_431_p2 = dpValues_q0 << 32'd4;

assign r_V_11_fu_447_p1 = r_V_9_fu_437_p4;

assign r_V_4_fu_451_p2 = (r_V_11_fu_447_p1 ^ r_V_10_fu_431_p2);

assign r_V_6_fu_487_p2 = dpValues_q0 << 32'd4;

assign r_V_7_fu_493_p4 = {{dpValues_q0[31:5]}};

assign r_V_8_fu_503_p1 = r_V_7_fu_493_p4;

assign r_V_9_fu_437_p4 = {{dpValues_q0[31:5]}};

assign r_V_fu_507_p2 = (r_V_8_fu_503_p1 ^ r_V_6_fu_487_p2);

assign tmp_10_fu_415_p1 = sum_i[1:0];

assign tmp_12_fu_519_p1 = sum_i[31:0];

assign tmp_14_fu_463_p1 = sum_i[31:0];

assign tmp_2_fu_523_p2 = (tmp_12_fu_519_p1 + temp_i);

assign tmp_3_fu_410_p1 = p_Result_1_fu_400_p4;

assign tmp_4_fu_457_p2 = (r_V_4_fu_451_p2 + dpValues_q0);

assign tmp_6_fu_467_p2 = (tmp_14_fu_463_p1 + temp_i);

assign tmp_7_fu_542_p2 = ((command == 2'd3) ? 1'b1 : 1'b0);

assign tmp_8_fu_536_p2 = ((command == 2'd2) ? 1'b1 : 1'b0);

assign tmp_9_fu_419_p1 = tmp_10_fu_415_p1;

assign tmp_read_fu_144_p2 = fsmState;

assign tmp_s_fu_513_p2 = (r_V_fu_507_p2 + dpValues_q0);

assign v_V_13_fu_529_p2 = (tmp_s_fu_513_p2 ^ tmp_2_fu_523_p2);

assign v_V_15_fu_480_p2 = (sum_i + 64'd2654435769);

assign v_V_17_fu_473_p2 = (tmp_6_fu_467_p2 ^ tmp_4_fu_457_p2);

assign v_V_21_fu_424_p2 = ($signed(sum_i) + $signed(64'd18446744071055115847));

assign values_address0 = 64'd0;

assign values_address1 = 64'd1;

assign xtea_dpValues_Val_V_10_gep_fu_337_p3 = 64'd1;

assign xtea_dpValues_Val_V_12_gep_fu_328_p3 = 64'd1;

assign xtea_dpValues_Val_V_14_gep_fu_319_p3 = 64'd0;

assign xtea_dpValues_Val_V_5_gep_fu_275_p3 = 64'd1;

assign xtea_dpValues_Val_V_6_gep_fu_266_p3 = 64'd0;

assign xtea_dpValues_Val_V_7_gep_fu_346_p3 = 64'd0;

assign xtea_dpValues_Val_V_8_gep_fu_243_p3 = 64'd0;

assign xtea_dpValues_Val_V_9_gep_fu_234_p3 = 64'd1;

assign xtea_dpValues_Val_V_s_gep_fu_355_p3 = 64'd0;

endmodule //xtea_datapath
